# Generated by Django 5.0.4 on 2024-04-14 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='SimilarUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('jj', models.CharField(max_length=255)),
                ('tiktok_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_users', to='mediaCrawlerApp.tiktokuser')),
            ],
        ),
        migrations.CreateModel(
            name='LiveStreamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('tiktok_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_stream_videos', to='mediaCrawlerApp.tiktokuser')),
            ],
        ),
    ]
