# Generated by Django 5.0.4 on 2024-05-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaCrawlerApp', '0003_similaruser_user_id_tiktokuser_mutable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokuser',
            name='is_searched',
            field=models.BooleanField(default=False),
        ),
    ]
