# Generated by Django 5.0.4 on 2024-06-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaCrawlerApp', '0004_tiktokuser_is_searched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similaruser',
            name='tiktok_user',
        ),
        migrations.DeleteModel(
            name='LiveStreamVideo',
        ),
        migrations.DeleteModel(
            name='SimilarUser',
        ),
        migrations.DeleteModel(
            name='TikTokUser',
        ),
    ]
